bifromq-inbox/bifromq-inbox-store/src/main/java/com/baidu/bifromq/inbox/store/InboxStoreCoProc.java
bifromq-inbox/bifromq-inbox-store/src/test/java/com/baidu/bifromq/inbox/store/InboxCreateTest.java

if the inbox is not existed, complete the missing part of the metadata.

Add qos2 seq and clientInfo for creating inboxes

---

README.md
README.zh_Hans.md

Modify the readme to include links to documentation and instructions on how to use docker.

add docker&docs link in README

---

build/build-bifromq-starters/bin/bifromq-start.bat
build/build-bifromq-starters/bin/bifromq-start.sh
build/build-bifromq-starters/bin/standalone.sh

Optimization script check failure prompt

Optimization script check failure prompt

---

base-cluster/src/main/java/com/baidu/bifromq/basecluster/memberlist/AutoSeeder.java
base-cluster/src/test/java/com/baidu/bifromq/basecluster/memberlist/AutoSeederTest.java
base-kv/base-kv-raft/src/main/java/com/baidu/bifromq/basekv/raft/RaftNodeStateLeader.java
base-kv/base-kv-store-client/src/main/java/com/baidu/bifromq/basekv/client/BaseKVStoreClient.java
base-rpc/src/main/java/com/baidu/bifromq/baserpc/ManagedMessageStream.java
bifromq-inbox/bifromq-inbox-broker-server/src/main/java/com/baidu/bifromq/inbox/server/InboxFetchPipeline.java
bifromq-inbox/bifromq-inbox-broker-server/src/test/java/com/baidu/bifromq/inbox/server/InboxInsertTest.java
bifromq-inbox/bifromq-inbox-reader-client/src/main/java/com/baidu/bifromq/inbox/client/IInboxReaderClient.java
bifromq-inbox/bifromq-inbox-reader-client/src/main/java/com/baidu/bifromq/inbox/client/InboxReaderPipeline.java
bifromq-mqtt/bifromq-mqtt-server/src/main/java/com/baidu/bifromq/mqtt/handler/SendBufferCapacityHinter.java
bifromq-mqtt/bifromq-mqtt-server/src/main/java/com/baidu/bifromq/mqtt/handler/v3/MQTT3PersistentSessionHandler.java
bifromq-mqtt/bifromq-mqtt-server/src/main/java/com/baidu/bifromq/mqtt/handler/v3/MQTT3SessionHandler.java
bifromq-mqtt/bifromq-mqtt-server/src/test/java/com/baidu/bifromq/mqtt/handler/BaseMQTTTest.java
bifromq-mqtt/bifromq-mqtt-server/src/test/java/com/baidu/bifromq/mqtt/handler/v3/MQTTPersistentS2CPubTest.java
build/build-bifromq-starters/src/main/java/com/baidu/bifromq/starter/StandaloneStarter.java
build/build-bifromq-starters/src/main/java/com/baidu/bifromq/starter/config/standalone/StandaloneConfig.java
build/build-bifromq-starters/src/main/java/com/baidu/bifromq/starter/config/standalone/StandaloneConfigConsolidator.java
build/build-bifromq-starters/src/main/java/com/baidu/bifromq/starter/config/standalone/model/RPCServerConfig.java

1. Add close notify for msgSubject int ManagedMessageStream.
3. Fix hint interaction logic for mqtt-server and inbox-server.
4. Add rpcServerConfig for baseKVShared RPC server.

Add come bugfixes

---

bifromq-inbox/bifromq-inbox-store/src/main/java/com/baidu/bifromq/inbox/store/InboxStoreCoProc.java
bifromq-inbox/bifromq-inbox-store/src/test/java/com/baidu/bifromq/inbox/store/MockedInboxAdminTest.java
bifromq-inbox/bifromq-inbox-store/src/test/java/com/baidu/bifromq/inbox/store/MockedInboxCommitTest.java
bifromq-inbox/bifromq-inbox-store/src/test/java/com/baidu/bifromq/inbox/store/MockedInboxFetchTest.java
bifromq-inbox/bifromq-inbox-store/src/test/java/com/baidu/bifromq/inbox/store/MockedInboxInsertTest.java
bifromq-inbox/bifromq-inbox-store/src/test/java/com/baidu/bifromq/inbox/store/QoS0InboxTest.java
bifromq-inbox/bifromq-inbox-store/src/test/java/com/baidu/bifromq/inbox/store/QoS1InboxTest.java

1. add some unit test in mock fashion;
2. correct some tests;
3. correct issues in coProc.

add unit tests for inboxStore

---

bifromq-inbox/bifromq-inbox-store/src/test/java/com/baidu/bifromq/inbox/store/MockedInboxAdminTest.java
bifromq-inbox/bifromq-inbox-store/src/test/java/com/baidu/bifromq/inbox/store/MockedInboxCommitTest.java
bifromq-inbox/bifromq-inbox-store/src/test/java/com/baidu/bifromq/inbox/store/MockedInboxFetchTest.java
bifromq-inbox/bifromq-inbox-store/src/test/java/com/baidu/bifromq/inbox/store/MockedInboxInsertTest.java
bifromq-inbox/bifromq-inbox-store/src/test/java/com/baidu/bifromq/inbox/store/MockedInboxStoreTest.java
bifromq-inbox/bifromq-inbox-store/src/test/java/com/baidu/bifromq/inbox/store/MockedInboxSubUnsubTest.java

1. add sub and unsub tests;2. refactoring the tests.

1. add sub and unsub tests;

---

base-kv/base-kv-store-balance-controller/src/main/java/com/baidu/bifromq/basekv/balance/KVRangeBalanceController.java
base-kv/base-kv-store-balance-controller/src/main/java/com/baidu/bifromq/basekv/balance/impl/RangeLeaderBalancer.java
base-kv/base-kv-store-balance-controller/src/main/java/com/baidu/bifromq/basekv/balance/impl/ReplicaCntBalancer.java
base-kv/base-kv-store-balance-controller/src/test/java/com/baidu/bifromq/basekv/balance/TestReplicaCntBalancerFactory.java
base-kv/base-kv-store-balance-controller/src/test/java/com/baidu/bifromq/basekv/balance/impl/RangeLeaderBalancerTest.java
base-kv/base-kv-store-server/src/main/java/com/baidu/bifromq/basekv/server/BaseKVStoreService.java
bifromq-dist/bifromq-dist-worker/src/main/java/com/baidu/bifromq/dist/worker/balance/ReplicaCntBalancerFactory.java
bifromq-inbox/bifromq-inbox-store/src/main/java/com/baidu/bifromq/inbox/store/balance/RangeLeaderBalancerFactory.java
bifromq-inbox/bifromq-inbox-store/src/main/java/com/baidu/bifromq/inbox/store/balance/ReplicaCntBalancerFactory.java
bifromq-inbox/bifromq-inbox-store/src/main/resources/META-INF/services/com.baidu.bifromq.basekv.balance.IStoreBalancerFactory
bifromq-retain/bifromq-retain-store/src/main/java/com/baidu/bifromq/retain/store/balance/ReplicaCntBalancerFactory.java

Simplify some logics in ReplicaCntBalancer and move RangeLeaderBalancer.

Feat inbox store leader balancer

---

base-cluster/src/test/java/com/baidu/bifromq/basecluster/AgentTestTemplate.java
bifromq-apiserver/src/main/java/com/baidu/bifromq/apiserver/utils/TopicUtil.java
bifromq-inbox/bifromq-inbox-server/src/main/java/com/baidu/bifromq/inbox/server/InboxFetcherRegistry.java
bifromq-inbox/bifromq-inbox-server/src/main/java/com/baidu/bifromq/inbox/server/InboxService.java
bifromq-inbox/bifromq-inbox-server/src/main/java/com/baidu/bifromq/inbox/server/scheduler/InboxCheckScheduler.java
bifromq-inbox/bifromq-inbox-server/src/main/java/com/baidu/bifromq/inbox/server/scheduler/InboxFetchScheduler.java
bifromq-inbox/bifromq-inbox-server/src/test/java/com/baidu/bifromq/inbox/server/InboxFetcherRegistryTest.java
bifromq-inbox/bifromq-inbox-server/src/test/java/com/baidu/bifromq/inbox/server/MockedInboxAdminTest.java
bifromq-inbox/bifromq-inbox-server/src/test/java/com/baidu/bifromq/inbox/server/MockedInboxMessageTest.java
bifromq-inbox/bifromq-inbox-server/src/test/java/com/baidu/bifromq/inbox/server/MockedInboxService.java
build/build-bifromq-starters/src/main/java/com/baidu/bifromq/starter/config/standalone/model/apiserver/listener/HttpsListenerConfig.java

1. add ut cases in mocked fashion for InboxService; 2. change some issues in InboxService.

InboxService ut complete

---

.github/ISSUE_TEMPLATE/bug_report.md

1. add some requirements for bug report.

1. add some requirements for bug report.

---

bifromq-mqtt/bifromq-mqtt-server/src/main/java/com/baidu/bifromq/mqtt/handler/MQTTTransientSessionHandler.java

1. add session route before call dist service.

fix issue #115

---

bifromq-mqtt/bifromq-mqtt-broker-client/pom.xml
bifromq-mqtt/bifromq-mqtt-broker-client/src/main/java/com/baidu/bifromq/mqtt/inbox/MqttBrokerClient.java
bifromq-mqtt/bifromq-mqtt-broker-client/src/main/java/com/baidu/bifromq/mqtt/inbox/MqttBrokerClientBuilder.java
bifromq-mqtt/bifromq-mqtt-broker-client/src/test/java/com/baidu/bifromq/mqtt/inbox/MqttBrokerClientTest.java

1. map ServerUnreachableException and ServerNotFoundException to NO_SUB

Exception mapping for shared subscription

---

bifromq-inbox/bifromq-inbox-server/src/test/java/com/baidu/bifromq/inbox/server/Fixtures.java
bifromq-inbox/bifromq-inbox-server/src/test/java/com/baidu/bifromq/inbox/server/InboxWriterPipelineTest.java
bifromq-inbox/bifromq-inbox-server/src/test/java/com/baidu/bifromq/inbox/server/InboxWriterTest.java

add inboxWriter and InboxWriterPipeline tests

add inboxWriter and InboxWriterPipeline tests

---

README.md
README.zh_Hans.md

1. add docker compose description for README.

add docker compose description for README.

---

.github/workflows/release.yaml
checkstyle.xml

1. Update the release workflows file
2. Update checkstyle to prohibit multiple consecutive blank lines

Update the release workflows file and checkstyle file.

---

README.md
README.zh_Hans.md

1. fix output dir error in README.

Fix output dir error in README.

---

NOTICE

All ASF projects are required to include a NOTICE file in every release.

add notice file

---

build/build-bifromq-starters/src/main/resources/log4j2.xml
build/build-plugin-demo/pom.xml

1. Fixed incorrect fully qualified name of the main function in the demo plugin.
2. Added project console log.

Fixed incorrect fully qualified name of the main function in the demo plugin.

---

bifromq-dist/bifromq-dist-worker/src/main/java/org/apache/bifromq/dist/worker/DeliverExecutorGroup.java
bifromq-dist/bifromq-dist-worker/src/test/java/org/apache/bifromq/dist/worker/DistQoS0Test.java

1. fix ordered share matching key error.

Fix ordered share matching key error.

---

bifromq-mqtt/bifromq-mqtt-server/src/main/java/org/apache/bifromq/mqtt/handler/ConnectionRateLimitHandler.java
bifromq-mqtt/bifromq-mqtt-server/src/main/java/org/apache/bifromq/mqtt/handler/ws/WebSocketOnlyHandler.java
bifromq-mqtt/bifromq-mqtt-server/src/test/java/org/apache/bifromq/mqtt/handler/ConnectionRateLimitHandlerTest.java
bifromq-mqtt/bifromq-mqtt-server/src/test/java/org/apache/bifromq/mqtt/handler/ws/WebSocketOnlyHandlerTest.java

1. release received bytebuf when failed to upgrade ws
2. release received bytebuf when connection rejected due to rate limiting

Fixed(#163) potential bytebuf leaks in two edge cases

---

bifromq-mqtt/bifromq-mqtt-server/src/main/java/org/apache/bifromq/mqtt/handler/v3/MQTT3ProtocolHelper.java
bifromq-mqtt/bifromq-mqtt-server/src/main/java/org/apache/bifromq/mqtt/handler/v5/MQTT5ProtocolHelper.java
bifromq-mqtt/bifromq-mqtt-server/src/test/java/org/apache/bifromq/mqtt/handler/v3/MQTT3TransientSessionHandlerTest.java
bifromq-mqtt/bifromq-mqtt-server/src/test/java/org/apache/bifromq/mqtt/handler/v5/TransientSessionHandlerTest.java

Adjust the backpressure strategy for MQTT 3 and MQTT 5. ‌ According to the MTTT protocol, adjust to return an error code or not respond, and throw a ServerBusy event.

Adjust the backpressure strategy for MQTT 3 and MQTT 5.
